// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

#pragma once
#include <string>

namespace GameLift
{
    namespace Configuration
    {
        static const std::string DO_NOT_EDIT = "#\n# DO NOT MANUALLY EDIT\n#\n# Autogenerated by AWS GameLift\n#\n";
    }
}