# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
# THIS IS A SAMPLE CLOUDFORMATION PARAMETERS FILE
GameNameParameter:
  value: "{{AWSGAMELIFT::SYS::GAMENAME}}"
LambdaZipS3BucketParameter:
  value: "{{AWSGAMELIFT::VARS::LambdaZipS3BucketParameter}}"
LambdaZipS3KeyParameter:
  value: "{{AWSGAMELIFT::VARS::LambdaZipS3KeyParameter}}"
ApiGatewayStageNameParameter:
  value: "{{AWSGAMELIFT::VARS::ApiGatewayStageNameParameter}}"
BuildS3BucketParameter:
  value: "{{AWSGAMELIFT::VARS::BuildS3BucketParameter}}"
BuildS3KeyParameter:
  value: "{{AWSGAMELIFT::VARS::BuildS3KeyParameter}}"
LaunchPathParameter:
  value: "{{AWSGAMELIFT::VARS::LaunchPathParameter}}"
LaunchParametersParameter:
  value: "-port=7777 -UNATTENDED LOG=server.log"
BuildNameParameter:
  value: "Sample GameLift Build for {{AWSGAMELIFT::SYS::GAMENAME}}"
BuildVersionParameter:
  value: "1"
BuildOperatingSystemParameter:
  value: "{{AWSGAMELIFT::VARS::BuildOperatingSystemParameter}}"
BuildServerSdkVersionParameter:
  value: "5.0.2"
FleetTcpFromPortParameter:
  value: "7770"
FleetTcpToPortParameter:
  value: "7780"
FleetUdpFromPortParameter:
  value: "7770"
FleetUdpToPortParameter:
  value: "7780"
FleetNameParameter:
  value: "FlexMatch Fleet"
UnrealEngineVersionParameter:
  value: "{{AWSGAMELIFT::VARS::UnrealEngineVersionParameter}}"

